### PR TITLE
Draft vignette of The Bank Tutorial Part 1 from SimPy v2

### PR DESCRIPTION
**Pull request by nacnudus**
First draft.  Sorry this took so long.  The section "More customers" is a bit hacky -- see #65.

### CODE REVIEW

**Comment by Enchufa2** [comment]
Awesome job, thank you very much! Some comments:
- As I said in #65, `every` is going to be removed, because, since #65, its behaviour can be easily replicated with `function() c(...)`. Please, use its old recipe to define this `wait` function, as you already did, and remove the references to `every`.
- I would like this vignette (and future parts) to appear right after `Advanced Trajectory Usage`. So, please, rename the files as
  - D-bank-1.Rmd
  - E-queueing-systems.Rmd
  - F-ctmc.Rmd
- Please, specify `{r, message=FALSE}` in those chunks where you load `dplyr` in order to hide the attaching messages.
- Of course, if you wish, you can use Python chunks in order to make comparisons, etc. Also your judgement is welcome: "this is easier with SimPy, this is more intuitive with simmer"... what you feel is appropriate. :wink:

**Comment by nacnudus** [comment]
Useful comments, thanks.
- Instead of `every`, I've used it's old recipe and called it `loop`. Since it's a slightly fancy use of environments, I've linked to Advanced R rather than explain exactly how it works.
- Might SimPy comparisons be better in a separate vignette?  Then the Bank ones would be suitable for teaching a pure simmer class.

**Comment by Enchufa2** [comment]
> Instead of `every`, I've used it's old recipe and called it `loop`. Since it's a slightly fancy use of environments, I've linked to Advanced R rather than explain exactly how it works.

Very appropriate. Maybe it's worth mentioning also that this kind of construction is called _closure_ in R.

> Might SimPy comparisons be better in a separate vignette?  Then the Bank ones would be suitable for teaching a pure simmer class.

Ok. Totally agree.

BTW, there is still a chunk using `every`.

**Comment by nacnudus** [comment]
Oops.  Mentioned _closure_, removed the stray _every_ chunk, and squashed the commits.

**Comment by Enchufa2** [comment]
Perfect! Thanks again! Merging...

**Pull request merged**
