### PR TITLE
added queueing support

### PR DESCRIPTION
**Pull request by Enchufa2**
I emailed you some hours ago about this feature. Then I started peering at the code and... here it is. Maybe it is rudimentary, and of course the documentation needs to be updated, but I think it works fine.

### CODE REVIEW

**Comment by Enchufa2** [comment]
I'm not sure if I fully understand your event-based framework. Currently, my patch implements the queueing support within the seize event, but I'm assuming that events happen in an orderly way, i.e., that the current entity is the first in the queue when it can seize the resource.

If the above assumption is not true, maybe we would need a separate vector holding the queue for each resource...

**Comment by bart6114** [comment]
@Enchufa2, thanks for the additions, much appreciated. 

Indeed, the queue works according to a FIFO system. In the initialization phase all entities get added to the model (in order of creation) and then their first activity/event is initialized and an early start time for the event is set. When the early start time has been reached the entities event will be considered for starting.

https://github.com/Enchufa2/simmer/blob/7535b00d0296f7919e74d36bc5e216f4bebf02be/src/event.h#L99-L107: I'm not sure why it has to be previously enqueued? Maybe it can be done there directly, I think it would save unnecessary iterations.

https://github.com/Enchufa2/simmer/blob/7535b00d0296f7919e74d36bc5e216f4bebf02be/src/simulator.h#L152: this means that none of the following activities of this entity will start. I can think of a scenario in which an entity abandons a queue, skips the event, but continuous with the next activity in its overall trajectory. What do you think?

**Comment by Enchufa2** [comment]
> https://github.com/Enchufa2/simmer/blob/7535b00d0296f7919e74d36bc5e216f4bebf02be/src/event.h#L99-L107: I'm not sure why it has to be previously enqueued? Maybe it can be done there directly, I think it would save unnecessary iterations.

Let us consider a system with one resource consisting of a queue and one server. Suppose there are 2 customers in the queue and one other being served. We are [here](https://github.com/Enchufa2/simmer/blob/7535b00d0296f7919e74d36bc5e216f4bebf02be/src/simulator.h#L136-L186). The customer in the server has already exhausted its timeout previously and now releases the resource. Then, a new customer's _seize_ event is processed. Although the server is free, this customer must be enqueued because those two in the queue must have priority over it.

> https://github.com/Enchufa2/simmer/blob/7535b00d0296f7919e74d36bc5e216f4bebf02be/src/simulator.h#L152: this means that none of the following activities of this entity will start. I can think of a scenario in which an entity abandons a queue, skips the event, but continuous with the next activity in its overall trajectory. What do you think?

I was thinking on queueing systems, where a customer arriving into a full queue is dropped. But indeed you are right: your scenario would be possible and should be supported. However, this means that the _seize_ and _release_ events (and everything between them) must be _linked_ somehow in order to avoid them. Am I right?

**Comment by bart6114** [comment]
OK. In essence the seize and release events are linked through the entity (they are all in the event vector of the entity), but at the moment it would be difficult to make out which release belongs to which seize event. I'll add it to the TODOs.

I'll do the merge this evening.

**Comment by Enchufa2** [comment]
In the current implementation, the method `get_event()` extracts the event from the entity's event list. This way, the events can be freed outside safely. But (and I'm thinking as a C programmer, not a C++ one, so I can be wrong) not freeing the events until the end of the simulation would be more efficient (specifically, the `erase()` method is very inefficient). The method `get_event()` would return a pointer without erasing the event from the list, and it would update an internal counter storing the next event. This way,
- Dropping an entity from a resource would involve incrementing the internal counter up to the event after the following _release_.
- Events must not be freed outside the `entity` class. Entities will become entirely responsible of destroying its own events.

I could work on these aspects for a future pull request if you agree. Also, my _C eye_ says that the event queue management is another point that can be reimplemented more efficiently. But I have to think more deeply on this.

By the way, I detected that, if you reduce the rate of incoming entities (without varying the number of entities, the interarrival times are, say, an order of magnitude higher), the simulation time grows inexplicably. Any clues?

**Comment by bart6114** [comment]
Nice suggestions. All improvement suggestions are very welcome! :) As said, it'll probably be May when I get some free time to work on it. I will however try to implement a few basic simulations in the package's tests to make sure the results are consistent and correct.

Regarding your last question, I've got no ideas off the top of my head... I'll try to do some tests later.

I've merged your additions into the master branch.

**Comment by Enchufa2** [comment]
And I've fetched the changes into my fork. :-)

Regarding the simulation time, the function `get_next_step()` increments the current time [one by one](https://github.com/Bart6114/simmer/blob/master/src/simulator.h#L31). But we can know the exact start and end times of each event:
- The start_time of the first event is equal to the entity's activation_time.
- The end_time of non-timed events is equal to the event's start_time.
- The end_time of timed events is equal to the event's start_time + duration.
- The start_time of each event (except the first one) is equal to the end_time of the previous event.

So it would be much more efficient to jump from one of these times to another rather than sweep the entire duration one by one. And the simulation would take the same time regardless of the rate of incoming entities.

**Comment by bart6114** [comment]
Fully agree, that was one of the quickly implement now, look at it later bits :)

**Pull request merged**
